# Generated by Django 4.0.4 on 2022-05-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
