# Generated by Django 4.0.4 on 2022-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0004_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
            ],
        ),
    ]
