# Generated by Django 4.0.4 on 2022-06-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0005_sendemailuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendemailuser',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
