# Generated by Django 4.0.4 on 2022-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0006_rename_create_at_sendemailuser_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, verbose_name='店舗名')),
                ('companyPostCode', models.CharField(max_length=11, verbose_name='郵便番号')),
                ('companyAddress', models.CharField(max_length=300, verbose_name='住所')),
                ('companyPhoneNumber', models.CharField(max_length=54, verbose_name='電話番号')),
                ('companyFax', models.CharField(blank=True, max_length=54, null=True, verbose_name='FAX')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
            ],
        ),
    ]
