# Generated by Django 4.0.4 on 2022-06-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0007_companies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
    ]
